### ISSUE TITLE
Photo API

### ISSUE THREAD

**Issue by goliatone** [martinruenz/v360#2]
Any directions on how to access the endpoints of the photo API? Wondering how to take pictures.

**Comment by martinruenz** [comment]
Hey,
sorry for my late response. I just added a function called "takePicture". You can also find an example here: https://github.com/martinruenz/v360/blob/master/examples/take_picture.py

**Comment by goliatone** [comment]
Thank you, I ended up making the method myself. Added a few other things, not sure if you are interested in PRs?

**Comment by martinruenz** [comment]
Sure! :octocat:
